# Generated by Django 3.1.7 on 2021-02-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Cash', 'Cash'), ('Plantation', 'Plantation'), ('Horticulture', 'Horticulture')], default='Food', max_length=30)),
                ('name', models.CharField(choices=[('rice', 'rice'), ('wheat', 'wheat'), ('millets', 'millets'), ('pulses', 'pulses'), ('oil', 'oil'), ('seeds', 'seeds'), ('cotton', 'cotton'), ('jute', 'jute')], default='rice', max_length=20)),
                ('variety', models.CharField(blank=True, max_length=15, null=True)),
                ('avail_weight', models.SmallIntegerField(blank=True, null=True)),
                ('quantity', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
