# Generated by Django 3.1.7 on 2021-02-21 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketdemo', '0002_auto_20210221_0708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('unit_price',)},
        ),
    ]
