# Generated by Django 3.1.7 on 2021-02-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdemo', '0004_auto_20210222_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='seller_phone',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[(0, 'Food'), (1, 'Cash'), (2, 'Plantation'), (3, 'Horticulture')], default=0, max_length=30, verbose_name='Category of Crop'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(choices=[(0, 'rice'), (1, 'wheat'), (2, 'millets'), (3, 'pulses'), (4, 'oil'), (5, 'seeds'), (6, 'cotton'), (7, 'jute')], default=0, max_length=20, verbose_name='Type of Category'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active Status'),
        ),
    ]
