# Generated by Django 3.1.7 on 2021-02-23 20:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('marketdemo', '0005_auto_20210223_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('vertical', models.CharField(choices=[(0, 'farming'), (1, 'insurance')], default=0, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('reg_no', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('price_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('price_km', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('status', models.CharField(choices=[(0, 'inactive'), (1, 'inprogress'), (2, 'delivered'), (3, 'abandoned')], default=0, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('payment_type', models.CharField(choices=[(0, 'PayTM'), (1, 'Credit Card'), (2, 'Debit Card'), (3, 'PayPal')], default=0, max_length=20)),
                ('ifsc', models.CharField(default=uuid.uuid4, max_length=50)),
                ('auth_id', models.CharField(default=uuid.uuid4, max_length=50)),
                ('status', models.CharField(choices=[(0, 'inactive'), (1, 'inprogress'), (2, 'failed'), (3, 'completed')], default=0, max_length=20)),
                ('acc_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
    ]
