# Generated by Django 3.1.7 on 2021-02-24 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketdemo', '0006_buyer_delivery_escrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='location_id',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('order_date', models.DateTimeField(auto_now=True, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('reqd_date', models.DateField(blank=True, null=True)),
                ('reqd_weight', models.SmallIntegerField(blank=True, null=True)),
                ('quantity', models.SmallIntegerField(blank=True, null=True)),
                ('delivery_pickup', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[(0, 'inactive'), (1, 'inprogress'), (2, 'delivered'), (3, 'abandoned')], default=0, max_length=15)),
                ('buyer_id', models.ForeignKey(db_column='buyer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketdemo.buyer')),
                ('location_id', models.ForeignKey(db_column='location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketdemo.location')),
                ('payment_id', models.ForeignKey(db_column='payment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketdemo.escrow')),
                ('product_id', models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketdemo.product')),
                ('reg_no', models.ForeignKey(db_column='reg_no', null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketdemo.delivery')),
                ('seller_id', models.ForeignKey(db_column='seller_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketdemo.seller')),
            ],
        ),
    ]
