# Generated by Django 3.1.7 on 2021-02-26 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketdemo', '0008_seller_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name_plural': 'Deliveries'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('reqd_date',)},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='vertical',
            field=models.CharField(choices=[('farming', 'farming'), ('insurance', 'insurance')], default='farming', max_length=50),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('inprogress', 'inprogress'), ('delivered', 'delivered'), ('abandoned', 'abandoned')], default='inactive', max_length=15),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='payment_type',
            field=models.CharField(choices=[('PayTM', 'PayTM'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('PayPal', 'PayPal')], default='PayTM', max_length=20),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('inprogress', 'inprogress'), ('failed', 'failed'), ('completed', 'completed')], default='inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='land',
            name='location_id',
            field=models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='land', to='marketdemo.location'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer_id',
            field=models.ForeignKey(db_column='buyer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='marketdemo.buyer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='location_id',
            field=models.ForeignKey(db_column='location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='marketdemo.location'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.ForeignKey(db_column='payment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='marketdemo.escrow'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='marketdemo.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reg_no',
            field=models.ForeignKey(db_column='reg_no', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='marketdemo.delivery'),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller_id',
            field=models.ForeignKey(db_column='seller_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='marketdemo.seller'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('inprogress', 'inprogress'), ('delivered', 'delivered'), ('abandoned', 'abandoned')], default='inactive', max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Cash', 'Cash'), ('Plantation', 'Plantation'), ('Horticulture', 'Horticulture')], default='Food', max_length=30, verbose_name='Category of Crop'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(choices=[('rice', 'rice'), ('wheat', 'wheat'), ('millets', 'millets'), ('pulses', 'pulses'), ('oil', 'oil'), ('seeds', 'seeds'), ('cotton', 'cotton'), ('jute', 'jute')], default='rice', max_length=20, verbose_name='Type of Category'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='land_id',
            field=models.ForeignKey(db_column='land_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='land', to='marketdemo.land'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seller',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='marketdemo.product'),
        ),
    ]
