# Generated by Django 3.1.7 on 2021-02-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdemo', '0010_auto_20210227_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distance',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Cash', 'Cash'), ('Plantation', 'Plantation'), ('Horticulture', 'Horticulture')], default='Food', max_length=30, verbose_name='Crop_Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(choices=[('rice', 'rice'), ('wheat', 'wheat'), ('millets', 'millets'), ('pulses', 'pulses'), ('oil', 'oil'), ('seeds', 'seeds'), ('cotton', 'cotton'), ('jute', 'jute')], default='rice', max_length=20, verbose_name='Crop'),
        ),
    ]
